Repository Semantic-Org/Semantic-UI, pull requests merged in 2018-03, with the labels that each got.

#4510 Fix for #4183
  src/definitions/modules/dropdown.js
Labels: Evaluating Bug / Change

#6225 [Search] add disabled style
  src/definitions/modules/search.less
Labels: Enhancement

#6268 [Menu] Disabled menu items still changing state on hover
  src/definitions/collections/menu.less
Labels: Confirmed Bug
