Repository Semantic-Org/Semantic-UI, pull requests merged in 2018-06, with the labels that each got.

#6220 [Label] Use basicBackground in all basic rules
  src/definitions/elements/label.less
Labels: Enhancement

#6431 Fix #6429: [Icon] Wechat icon doesn't display
  .github/stale.yml
  src/themes/default/elements/icon.overrides
Labels: Evaluating Bug / Change

#6447 [Dependency] Add compatibility with Less 3.x
  RELEASE-NOTES.md
  src/README.md
  src/theme.config.example
  src/theme.less
  tasks/admin/components/init.js
  tasks/admin/components/update.js
  tasks/admin/distributions/update.js
Labels: Confirmed Bug, Needs Milestone
