Repository Semantic-Org/Semantic-UI, pull requests merged in 2018-02, with the labels that each got.

#6136 Add missing comma: makes 9 global vars local
  tasks/admin/components/init.js
Labels: Confirmed Bug

#6127 Cleanup documentation HTML structure
  examples/grid.html
  examples/responsive.html
  examples/sticky.html
Labels: Evaluating Bug / Change

#6059 [Popup] Use @background value for arrow background color
  src/themes/default/modules/popup.variables
Labels: Confirmed Bug

#4614 Take content settings before attr title
  src/definitions/modules/popup.js
Labels: Confirmed Bug

#4423 'on: change' causes error prompts to appear when blurring field
  src/definitions/behaviors/form.js
Labels: Evaluating Bug / Change

#4631 Fix inverted dimmer text color
  src/definitions/modules/dimmer.less
Labels: Confirmed Bug

#3396 [Modal] Support modification of 'closable' setting while modal is open
  src/definitions/modules/modal.js
Labels: Enhancement

#4157 [Icon Input] Fix for issue #4057
  src/definitions/elements/input.less
Labels: Evaluating Bug / Change

#5892 Added onChanging callback to accordion
  dist/semantic.js
Labels: Enhancement

#6182 Setup stalebot for stale issue management
  .github/stale.yml
Labels: Enhancement

#6181 Fixed the icon bugs raised in the issues
  src/themes/default/assets/fonts/icons.eot
  src/themes/default/assets/fonts/icons.svg
  src/themes/default/assets/fonts/icons.ttf
  src/themes/default/assets/fonts/icons.woff
  src/themes/default/assets/fonts/icons.woff2
  src/themes/default/elements/icon.overrides
Labels: Evaluating Bug / Change

#6205 Created issue template
  .github/ISSUE_TEMPLATE.md
Labels: Enhancement
